STUB_SERVER_URL_BASE = 'http://jenkins-undercurrent-stub.nimbus-03.cg.bskyb.com/'
SEMANTIC_INTEGRATION_SCENARIOS = STUB_SERVER_URL_BASE + 'scenarios/semantic-integration'
TEST_ACCOUNT_HAS_PRODUCTS_TARGET_URI = STUB_SERVER_URL_BASE + 'lws/get-customer-portfolio'
TEST_FIND_POM_PRODUCT_INFO_TARGET_URI = STUB_SERVER_URL_BASE + 'pom/getproducts'
MEMBER_BORROWED_BOOKS_SERVICE_TARGET_URI = STUB_SERVER_URL_BASE + 'library/member-borrowed-books'